name: on-push
on: push
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Push
        run: |
          echo "Event-Name: $GITHUB_EVENT_NAME"
          echo "Branch Ref: $GITHUB_REF"
          echo "Commit Sha: $GITHUB_SHA"
          echo "Pushed by: $GITHUB_ACTOR"
          
